import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import "tailwindcss/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-grotesk@400,300,500&display=swap"
          rel="stylesheet"
        />
        <script async src="js/main.js"></script>
      </Head>
      <body className="antialiased bg-body text-body font-body">
        {children}
      </body>
    </html>
  );
}
